Adding delete button to allow users to delete comments
3782291211/nc-news pull request #8
Opened 2023-01-11 12:07 UTC by 3782291211

Adding some restrictions and a confirmation message to let users know when a comment has been deleted

2023-01-11 12:17 UTC, popatre requested changes
Most of the way there, some stuff to add:

- I'd ideally only want to be able to delete my own comments, not everyone can delete everyone elses
- At the moment, if the api request doesnt work, it just constantly says `deleting...` despite the fact its failed. 
- Could you disable the button after its been clicked. Just so i cant keep clicking it on a slow internet connection?

-

2023-01-11 12:17 UTC, popatre commented on src/Components/VoteUpdateButtons.jsx
> +    setTimeout(() => setShowDeletedMsg(false), 5000);
What if it doesnt successfully delete?

2023-01-12 09:44 UTC, roisinoreilly approved these changes
really excellent work, the only thing I would suggest for this ticket is that the user shouldn't see a delete button for comments that aren't theirs, otherwise merge when ready

2023-01-12 09:44 UTC, roisinoreilly commented on src/App.js
> +      {useLocation().pathname !== '/' && <button onClick={() => window.scrollTo({
very nice

2023-01-12 09:44 UTC, roisinoreilly commented on src/Components/Buttons.jsx
> +const handleDelete = () => {
I think that we shouldn't be able to see a delete button for comments that aren't the logged in user, not just an error message

2023-01-12 09:44 UTC, roisinoreilly commented on src/Components/Comments.jsx
> +if (showDeletedMsg || showWrongUserMsg || showDeleteError) {
really nicely handled

2023-01-12 10:05 UTC, merged